# Generated by Django 5.1.7 on 2025-06-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_interview_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='resume',
        ),
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
