# Generated by Django 5.1.7 on 2025-06-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_student_resume_student_bio_student_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='projects',
            field=models.TextField(blank=True),
        ),
    ]
