# Generated by Django 5.1.7 on 2025-06-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_student_achievements_student_certifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='approved',
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
